<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522100809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_refresh_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F02938B8C74F2195 ON user_refresh_tokens (refresh_token)');
        $this->addSql('CREATE INDEX idx_user_refresh_tokens_token ON user_refresh_tokens (refresh_token)');
        $this->addSql('CREATE INDEX idx_user_refresh_tokens_username ON user_refresh_tokens (username)');
        $this->addSql('CREATE INDEX idx_user_refresh_tokens_valid ON user_refresh_tokens (valid)');
        $this->addSql('CREATE INDEX idx_user_refresh_tokens_user_id ON user_refresh_tokens (user_id)');
        $this->addSql('ALTER TABLE user_refresh_tokens ADD CONSTRAINT FK_F02938B8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_refresh_tokens DROP CONSTRAINT FK_F02938B8A76ED395');
        $this->addSql('DROP TABLE user_refresh_tokens');
    }
}
